# -*- coding: utf-8 -*-
"""Profanity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_6p0NgawU3edCcLQhtZEkau0T2iKFV9
"""

import pandas as pd
import re
import matplotlib.pyplot as plt

from google.colab import files
#Loading the Data set which has been downloaded from Data_download.ipynb
Uploaded_File=files.upload()

Data_log=pd.read_csv('load your data')

print("First 5 Tweets: \n")
for i in Data_log['Content'][:5]:
  print(i + "\n")

#Pre-processing or Text cleaning 
def Clean_text(text):
  text=re.sub(r'@[A-Za-z0-9]+', '',text)
  text=re.sub(r'#', '',text)
  text=re.sub(r'@_', '',text)
  text=re.sub(r'RT[/s]+', '',text)
  text=re.sub(r'https?:\/\/\S+', '',text)
  #text=re.sub(r'"_"','',text)
  return text

Data_log['Content']=Data_log['Content'].apply(Clean_text)

#racial slurs, define it
racial_slurs = ["slur0","slur1","slur2","slur3"] # Add your own racial slurs here

def profanity_score(sentence):
    words = sentence.split()
    #Calculate the number of racial slurs in the sentence
    num_slurs = len([word for word in words if word.lower() in racial_slurs])
    #Calculate the profanity score as a percentage of the number of words in the sentence
    return (num_slurs / len(words)) * 100 if len(words) > 0 else 0

Data_log['Degree of Profanity']=Data_log['Content'].apply(profanity_score)

def Num_slur(sentence):
  words = sentence.split()
  # Calculate the number of racial slurs in the sentence
  num_slurs = len([word for word in words if word.lower() in racial_slurs])
  return num_slurs

Data_log['Profanity']=Data_log['Content'].apply(Num_slur)

#Use this for profanity count or the above 
'''def count_words(sentence):
    counts = 0
    for word in sentence.split():
      if word in racial_slurs:
        counts += 1
    return counts'''

# Data_log['Profanity']=Data_log['Content'].apply(count_words)

Data_log[265:300]

#Analysing the tweets 
def Analysis(score):
  if score==0:
    return 'Non racial Tweet'
  else:
    return "Racial Tweet"

Data_log['Analysis']=Data_log['Profanity'].apply(Analysis)

#graphical representation
sns.set(style="whitegrid") 
# plotting strip plot with seaborn
# attributes of dataset
ax = sns.stripplot(x=Data_log['Degree of Profanity'], y=Data_log['Analysis'], data=Data_log)
plt.title('Slur Analysis')
plt.show()